# Store non-sensitive project configuration here
item_groups:
  - id: "milk"
    name: "Milk"
    icon: "https://cdn1.iconfinder.com/data/icons/barista/256/barista-icons_milk-package-512.png"
    shop_type: "grocery"
  - id: "cereal"
    name: "Cereal"
    icon: "https://cdn1.iconfinder.com/data/icons/smashicons-gastronomy-outline-vol-1/54/17_-_Cereals_gastronomy_food_cooking-512.png"
    shop_type: "grocery"
  - id: "meat"
    name: "Meat"
    icon: "https://cdn4.iconfinder.com/data/icons/food-and-equipment-outline/32/meat-512.png"
    shop_type: "grocery"
  - id: "eggs"
    name: "Eggs"
    icon: "https://cdn2.iconfinder.com/data/icons/easter-2034/48/10-Egg-512.png"
    shop_type: "grocery"
  - id: "bread"
    name: "Bread"
    icon: "https://cdn4.iconfinder.com/data/icons/food-and-equipment-outline/32/bread-512.png"
    shop_type: "grocery"
  - id: "beans"
    name: "Beans"
    icon: "https://cdn1.iconfinder.com/data/icons/vegetables-56/50/Vegetables_Outline-03-512.png"
    shop_type: "grocery"
  - id: "water"
    name: "Water"
    icon: "https://cdn0.iconfinder.com/data/icons/beverage/64/BOTTLED_WATER-512.png"
    shop_type: "grocery"
  - id: "toiletPaper"
    name: "ToiletPaper"
    icon: "https://cdn2.iconfinder.com/data/icons/free-line-halloween-icons/24/Toilet-Paper-512.png"
    shop_type: "grocery"
  - id: "fruits"
    name: "Fruits"
    icon: "https://cdn4.iconfinder.com/data/icons/fruits-and-veggies-2/241/fruits-and-veggies-icons_grape-512.png"
    shop_type: "grocery"
  - id: "fish"
    name: "Fish"
    icon: "https://cdn2.iconfinder.com/data/icons/miscellaneous-12/24/miscellaneous-66-512.png"
    shop_type: "grocery"
  - id: "sweets"
    name: "Sweets"
    icon: "https://cdn4.iconfinder.com/data/icons/free-line-christmas-icons/24/Candy-512.png"
    shop_type: "grocery"
  - id: "coffee"
    name: "Coffee"
    photo: "https://cdn3.iconfinder.com/data/icons/sympletts-free-sampler/128/coffee-cup-2-512.png"
    shop_type: "grocery"
  - id: "oats"
    name: "oats"
    icon: "https://cdn3.iconfinder.com/data/icons/thanks-giving-1/60/wheat__grain__crop__oats__agriculture-512.png"
    shop_type: "grocery"
  - id: "tea"
    name: "Tea"
    icon: "https://cdn4.iconfinder.com/data/icons/hotel-service-5/300/tea-512.png"
    shop_type: "grocery"
  - id: "nuts"
    name: "Nuts"
    icon: "https://cdn0.iconfinder.com/data/icons/maternity-and-pregnancy-2/512/79_Forest_Nuts_Seeds-512.png"
    shop_type: "grocery"
  - id: "painkillers"
    name: "Painkillers"
    icon: "https://cdn1.iconfinder.com/data/icons/emergency/24/painkiller_pill_morphine-512.png"
    shop_type: "pharmacy"
  - id: "coughSyrup"
    name: "CoughSyrup"
    photo: "https://cdn4.iconfinder.com/data/icons/food-and-beverage-11/640/syrup-512.png"
    shop_type: "pharmacy"
  - id: "handSanitizer"
    name: "HandSanitizer"
    icon: "https://cdn3.iconfinder.com/data/icons/minimal-disease/256/minimal_disease_2-512.png"
    shop_type: "pharmacy"
  - id: "bandaids"
    name: "Bandaids"
    icon: "https://cdn4.iconfinder.com/data/icons/medical-227/512/583_bandaid_beauty_health_injury-512.png"
    shop_type: "pharmacy"
  - id: "mask"
    name: "Mask"
    icon: "https://cdn0.iconfinder.com/data/icons/health-26/64/hygienic_mask-hygienic-mask-virus-512.png"
    shop_type: "pharmacy"
feedback_endpoint: "https://secret-mountain-57394.herokuapp.com"
app_url: "http://ec2-18-130-190-158.eu-west-2.compute.amazonaws.com:8010/"
