# Store non-sensitive project configuration here
item_groups:
  - id: "milk"
    name: "Milk"
  - id: "cereal"
    name: "Cereal"
  - id: "meat"
    name: "Meat"
  - id: "eggs"
    name: "Eggs"
  - id: "bread"
    name: "Bread"
  - id: "beans"
    name: "Beans"
  - id: "water"
    name: "Water"
  - id: "toiletPaper"
    name: "ToiletPaper"
  - id: "fruits"
    name: "Fruits"
  - id: "fish"
    name: "Fish"
  - id: "sweets"
    name: "Sweets"
  - id: "coffee"
    name: "Coffee"
  - id: "rice"
    name: "Rice"
  - id: "oats"
    name: "oats"
  - id: "tea"
    name: "Tea"
  - id: "nuts"
    name: "Nuts"
  - id: "painkillers"
    name: "Painkillers"
  - id: "coughSyrup"
    name: "CoughSyrup"
  - id: "handSanitizer"
    name: "HandSanitizer"
  - id: "bandaids"
    name: "Bandaids"
  - id: "lozenge"
    name: "Lozenge"
feedback_endpoint: "https://secret-mountain-57394.herokuapp.com"